# Generated by Django 4.1.3 on 2022-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='humidity',
            field=models.FloatField(null=True, verbose_name='습도'),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature',
            field=models.FloatField(null=True, verbose_name='온도'),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(max_length=10, unique=True, verbose_name='날짜'),
        ),
    ]
