# Generated by Django 4.1.3 on 2022-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0003_rename_time_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(max_length=19, unique=True, verbose_name='날짜'),
        ),
    ]
