# Generated by Django 4.1.3 on 2022-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_server', '0004_alter_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=19, unique=True, verbose_name='날짜'),
        ),
    ]
